### ISSUE TITLE
Separate files

### ISSUE THREAD

**Issue by tmills-usgs** [wfarmer-usgs/WREG#2]
I took a quick look and first thing I noticed is that each function should be its own .R file. Easy fix

**Comment by wfarmer-usgs** [comment]
Thanks, Joe.  Just so I understand, what's advantage to that?  When I was
developing, I read that it was essentially a style thing: to individualize
or not.

--
William H. Farmer
Research Physical Scientist
Office of Surface Water & National Research Program
U.S. Geological Survey

phone: (303) 236-4981
e-mail: wfarmer@usgs.gov

**Comment by tmills-usgs** [comment]
It just makes the package easier for someone else to follow. It is just a style thing, but unless you have a ton of 10-line long functions that are thematically similar (cough, EFLOWSTATS) its nice to be able to quickly go to the code for a particular function.
